# -*- coding: utf-8 -*-
"""生成 rollback_qoder_all.py 自包含版本：内嵌 compact+enhance 的 REVERSES。"""
import sys, ast

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# 从两个 patch 脚本提取 PATCHES（安全方式：exec 模块，仅取 PATCHES）
def get_patches(path):
    ns = {}
    src = open(path, encoding="utf-8").read()
    # 截取到 PATCHES 定义结束（避免执行其他顶层逻辑）
    exec(compile(src, path, "exec"), ns)
    return ns["PATCHES"]

pc = get_patches(r"c:\Users\53518\Documents\Qoder\2026-08-14\chat-3\compact\patch_qoder_compact.py")
pe = get_patches(r"c:\Users\53518\Documents\Qoder\2026-08-14\chat-3\enhance\patch_qoder_enhance.py")
print("compact PATCHES:", len(pc), "| enhance PATCHES:", len(pe))

reverses = [(new, old) for old, new in pc] + [(new, old) for old, new in pe]

# 生成自包含 rollback_qoder_all.py
lines = []
lines.append('# -*- coding: utf-8 -*-')
lines.append('"""')
lines.append('Qoder 压缩/优化输入 patch 统一回滚脚本（自包含版）')
lines.append('')
lines.append('精确逆向还原 compact（P1-P3）与 enhance（P-A~P-E）的全部 patch，')
lines.append('使 agents-window.desktop.main.js 回到本仓库修改前的状态。')
lines.append('**不影响专家团项目（experts/）的 patch**。')
lines.append('')
lines.append('用法：1) 完全退出 Qoder')
lines.append('      2) 右键本 bat -> 以管理员身份运行')
lines.append('      3) 重启 Qoder')
lines.append('')
lines.append('路径探测（可移植）：--js <bundle路径> 或环境变量 QODER_INSTALL_DIR 优先，')
lines.append('      否则自动探测常见安装位置。')
lines.append('"""')
lines.append('import os')
lines.append('import sys')
lines.append('import shutil')
lines.append('import datetime')
lines.append('')
lines.append('JS = r"C:\\Program Files\\Qoder\\resources\\app\\out\\lingma\\agents-window\\agents-window.desktop.main.js"')
lines.append('')
lines.append('')
lines.append('def detect_js():')
lines.append('    """探测 agents-window.desktop.main.js 路径：--js > QODER_INSTALL_DIR > 常见安装位置"""')
lines.append('    if "--js" in sys.argv:')
lines.append('        return sys.argv[sys.argv.index("--js") + 1]')
lines.append('    env = os.environ.get("QODER_INSTALL_DIR")')
lines.append('    rel = os.path.join("resources", "app", "out", "lingma", "agents-window", "agents-window.desktop.main.js")')
lines.append('    if env:')
lines.append('        return os.path.join(env, rel)')
lines.append('    for root in (r"C:\\Program Files\\Qoder", r"C:\\Program Files (x86)\\Qoder",')
lines.append('                 os.path.expandvars(r"%LOCALAPPDATA%\\Programs\\Qoder")):')
lines.append('        p = os.path.join(root, rel)')
lines.append('        if os.path.exists(p):')
lines.append('            return p')
lines.append('    return os.path.join(r"C:\\Program Files\\Qoder", rel)')
lines.append('')
lines.append('')
lines.append('TEST_MODE = "--test" in sys.argv')
lines.append('if TEST_MODE:')
lines.append('    JS = sys.argv[sys.argv.index("--test") + 1]')
lines.append('else:')
lines.append('    JS = detect_js()')
lines.append('')
lines.append('# 控制台 UTF-8 输出（避免 GBK 乱码）')
lines.append('for _s in (sys.stdout, sys.stderr):')
lines.append('    try:')
lines.append('        _s.reconfigure(encoding="utf-8", errors="replace")')
lines.append('    except Exception:')
lines.append('        pass')
lines.append('')
lines.append('# 反转表：[(当前patch后文本, 原始文本)] —— compact(P1-P3) + enhance(P-A~P-E)')
lines.append('REVERSES = [')
for new, old in reverses:
    lines.append("    (%r, %r)," % (new, old))
lines.append(']')
lines.append('')
lines.append('# 专家团 patch 标记（回滚后必须仍存在，防止误伤）')
lines.append('EXPERTS_MARKERS = [')
lines.append('    "_isCustomModelExists(e){return!!uie(e)}",          # P1')
lines.append('    "r===pn.EXPERTS?(this._availableModelConfigs.get(r)||[]).concat(",  # P2')
lines.append('    "re=(0,yl.useMemo)(()=>!1,[Q.userPlan,Q.userInfo,c])",  # P4')
lines.append(']')
lines.append('')
lines.append('')
lines.append('def main():')
lines.append('    if not TEST_MODE:')
lines.append('        tasklist = os.popen(\'tasklist /FO CSV /NH 2>nul\').read().lower()')
lines.append('        if "qoder" in tasklist:')
lines.append('            print("[!] Qoder 仍在运行，请先完全退出（含托盘）再执行。")')
lines.append('            sys.exit(1)')
lines.append('')
lines.append('    if not os.path.exists(JS):')
lines.append('        print("[!] 找不到目标文件（版本可能已更新）：", JS)')
lines.append('        sys.exit(2)')
lines.append('')
lines.append('    with open(JS, "r", encoding="utf-8", errors="replace") as f:')
lines.append('        content = f.read()')
lines.append('')
lines.append('    todo = []')
lines.append('    already = []')
lines.append('    for new, old in REVERSES:')
lines.append('        cnt_new = content.count(new)')
lines.append('        if cnt_new == 0:')
lines.append('            already.append(new)')
lines.append('            continue')
lines.append('        if old in content:')
lines.append('            print("[!] 原始代码段已存在（可能已回滚）:", old[:60], "...")')
lines.append('            already.append(new)')
lines.append('            continue')
lines.append('        if cnt_new in (1, 3):')
lines.append('            todo.append((new, old))')
lines.append('        else:')
lines.append('            print("[!] patch 文本出现 %d 次（预期 1 或 3），请人工确认:" % cnt_new, new[:60], "...")')
lines.append('            sys.exit(3)')
lines.append('')
lines.append('    if already:')
lines.append('        print("[*] %d 项无需回滚（未找到 patch 或已还原）" % len(already))')
lines.append('    if not todo:')
lines.append('        print("[*] 全部 patch 已回滚，无需操作。")')
lines.append('    else:')
lines.append('        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")')
lines.append('        bak = JS + ".bak_allrollback_" + ts')
lines.append('        shutil.copy2(JS, bak)')
lines.append('        print("[1/3] 已备份当前(patch)状态:", os.path.basename(bak))')
lines.append('')
lines.append('        for new, old in todo:')
lines.append('            content = content.replace(new, old)')
lines.append('        with open(JS, "w", encoding="utf-8", newline="") as f:')
lines.append('            f.write(content)')
lines.append('        print("[2/3] 已还原 %d 处 patch" % len(todo))')
lines.append('')
lines.append('    # 读回验证')
lines.append('    with open(JS, "r", encoding="utf-8", errors="replace") as f:')
lines.append('        check = f.read()')
lines.append('    miss = [old for _, old in REVERSES if old not in check]')
lines.append('    leftover = [new for new, _ in REVERSES if new in check]')
lines.append('    experts_ok = all(m in check for m in EXPERTS_MARKERS)')
lines.append('    print("[3/3] 原始代码段缺失:", len(miss), "| patch 残留:", len(leftover), "| 专家团 patch 保留:", experts_ok)')
lines.append('    if not miss and not leftover and experts_ok:')
lines.append('        print("      回滚验证通过。重启 Qoder 后压缩/优化输入恢复原始行为。")')
lines.append('    else:')
lines.append('        print("[!] 验证未全通过！请从备份恢复。")')
lines.append('        sys.exit(4)')
lines.append('')
lines.append('')
lines.append('if __name__ == "__main__":')
lines.append('    main()')

target = r"c:\Users\53518\Documents\Qoder\2026-08-14\chat-3\compact\rollback_qoder_all.py"
with open(target, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print("已生成自包含 rollback_qoder_all.py，REVERSES 条目:", len(reverses))
